config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :tenants
  #get 'home/index'
  root "home#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tenant.rb
class Tenant < ApplicationRecord
    #check we have input for all fields, phone and email in particular
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :apartment, presence: true
    validates :phone, presence: true, length: { minimum: 10, maximum: 10 }
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
   validates :title, presence: true
   validates :body, presence: true, length: { minimum: 20} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception, unless: -> {request.format.json?}
  
  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:first_name, :last_name, :apartment, :phone, :email)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  protect_from_forgery with: :exception, unless: -> {request.format.json?}
  
  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :body, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/home/index.html.erb
<h1>Building Management</h1>
<%= link_to "Tenants", "/tenants"%>
<%= link_to "Maintenance Tickets", "/tickets"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuildingManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to "Home", "http://localhost:3000/"%>
    <%= yield %>
  </body>
</html>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :apartment, style: "display: block" %>
    <%= form.text_field :apartment %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div id="<%= dom_id tenant %>">
  <p>
    <strong>First name:</strong>
    <%= tenant.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= tenant.last_name %>
  </p>

  <p>
    <strong>Apartment:</strong>
    <%= tenant.apartment %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= tenant.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= tenant.email %>
  </p>

</div>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Show this tenant", @tenant %> |
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tenants</h1>

<div id="tenants">
  <% @tenants.each do |tenant| %>
    <%= render tenant %>
    <p>
      <%= link_to "Show this tenant", tenant %>
    </p>
  <% end %>
</div>

<%= link_to "New tenant", new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tenant %>

<div>
  <%= link_to "Edit this tenant", edit_tenant_path(@tenant) %> |
  <%= link_to "Back to tenants", tenants_path %>

  <%= button_to "Destroy this tenant", @tenant, method: :delete %>
</div>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p>
    <strong>Title:</strong>
    <%= ticket.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= ticket.body %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= ticket.completed %>
  </p>

</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
    <p>
      <%= link_to "Show this ticket", ticket %>
    </p>
  <% end %>
</div>

<%= link_to "New ticket", new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Edit this ticket", edit_ticket_path(@ticket) %> |
  <%= link_to "Back to tickets", tickets_path %>

  <%= button_to "Destroy this ticket", @ticket, method: :delete %>
</div>